### ISSUE TITLE
SyntaxError: Unexpected identifier - import axios from './lib/axios.js';

### ISSUE THREAD

**Issue by francescor** [RafalWilinski/telegram-chatgpt-concierge-bot#1]
```
~/telegram-chatgpt-concierge-bot$ npm start

> telegram-gpt-bot@1.0.0 start /home/dante/telegram-chatgpt-concierge-bot
> ts-node src/index.ts

telegram-chatgpt-concierge-bot/node_modules/axios/index.js:1
import axios from './lib/axios.js';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dante/telegram-chatgpt-concierge-bot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/dante/telegram-chatgpt-concierge-bot/src/lib/downloadVoiceFile.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! telegram-gpt-bot@1.0.0 start: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the telegram-gpt-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    2023-04-10T10_13_25_914Z-debug.log
```

**Comment by pedroCX486** [comment]
Did you `npm install` first? This error is _usually_ thrown when a package isn't found.
