### ISSUE TITLE
error when running on Raspberry pi 4, armv7

### ISSUE THREAD

**Issue by hblink** [RafalWilinski/telegram-chatgpt-concierge-bot#17]
telegram-gpt-bot@1.0.0 start
> ts-node src/index.ts

papa@raspberrypi2:~/telegram-chatgpt-concierge-bot $ /home/papa/telegram-chatgpt-concierge-bot/node_modules/langchain/dist/agents/executor.cjs:48
            input.returnIntermediateSteps ?? this.returnIntermediateSteps;
                                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/home/papa/telegram-chatgpt-concierge-bot/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/papa/telegram-chatgpt-concierge-bot/node_modules/langchain/src/agents/index.ts:24:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR! code 1
npm ERR! path /home/papa/telegram-chatgpt-concierge-bot
npm ERR! command failed
npm ERR! command sh -c ts-node src/index.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/papa/.npm/_logs/2023-04-18T07_40_55_333Z-debug.log

can anyone help please?

**Comment by hblink** [comment]
any one can help?

**Comment by hblink** [comment]
here are the versions i am using
npm version
{
  'telegram-gpt-bot': '1.0.0',
  npm: '7.5.2',
  node: '12.22.12',
  v8: '7.8.279.23-node.57',
  uv: '1.40.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '72',
  nghttp2: '1.43.0',
  napi: '8',
  llhttp: '2.1.6',
  http_parser: '2.9.4',
  openssl: '1.1.1n',
  cldr: '37.0',
  icu: '67.1',
  tz: '2019c',
  unicode: '13.0'
}
papa@raspberrypi2:~/telegram-chatgpt-concierge-bot $ node -v
v12.22.12
